#!/usr/bin/env python3
"""Build one 20-second vertical short per division from shorts/divisions.json.

Scene timings are derived from the voiceover lengths in assets/voice/shorts/,
so after regenerating a voice line just run:  python3 shorts/build.py
"""
import html
import re
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VOICE = ROOT / "assets/voice/shorts"
TOTAL = 20.0
LEAD = 0.4   # silence before the first line
GAP = 0.2    # breathing room either side of a scene change


def seconds(wav: Path) -> float:
    out = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", str(wav)],
        capture_output=True, text=True, check=True,
    )
    return round(float(out.stdout), 2)


def contact() -> dict:
    """Read the CONTACT block from assets/brand.js so contact details live in one place."""
    src = (ROOT / "assets/brand.js").read_text()
    block = re.search(r"const CONTACT = \{(.*?)\};", src, re.S).group(1)
    return dict(re.findall(r'(\w+):\s*"([^"]*)"', block))


def esc(s: str) -> str:
    return html.escape(s, quote=False)


def build(div: dict) -> str:
    slug = div["slug"]
    lines = [VOICE / f"{slug}-{i}.wav" for i in (1, 2, 3)] + [VOICE / "cta.wav"]
    d = [seconds(p) for p in lines]

    # Scene starts: each scene holds its voice line plus a small gap.
    b = round(LEAD + d[0] + GAP, 2)
    c = round(b + GAP + d[1] + GAP, 2)
    dd = round(c + GAP + d[2] + GAP, 2)
    if dd + GAP + d[3] + 0.6 > TOTAL:
        raise SystemExit(f"{slug}: voiceover too long for {TOTAL}s ({dd + GAP + d[3] + 0.6:.2f}s)")
    starts = [LEAD, b + GAP, c + GAP, dd + GAP]
    T = {"b": b, "c": c, "d": dd, "end": TOTAL}

    audio = [
        f'<audio id="a-music" src="../assets/music/music-bed-20s.wav" data-start="0" data-duration="{TOTAL:g}" '
        f'data-track-index="10" data-volume="0.6" data-fade-out="1.5"></audio>'
    ]
    for i, (p, s, dur) in enumerate(zip(lines, starts, d), 1):
        audio.append(
            f'<audio id="a-vo-{i}" src="../assets/voice/shorts/{p.name}" data-start="{s:g}" '
            f'data-duration="{dur:g}" data-track-index="11"></audio>'
        )

    name = '<h1 class="name">TGM<span>-</span>WORLDWIDE</h1>'
    corp = '<p class="corp">CORPORATION</p>'
    division = f'<p class="division">{esc(div["name"])}</p>'
    items = "".join(f"<div>{esc(x)}</div>" for x in div["items"])
    cards = "".join(f'<div class="card"><em>{i}</em><span>{esc(t)}</span></div>' for i, t in div["benefits"])
    audio_html = "\n      ".join(audio)
    info = contact()
    rows = "\n        ".join(
        f'<div class="row {key}"><span>{esc(info[key])}</span></div>'
        for key in ("phone", "email", "website") if info.get(key)
    )

    return f"""<!doctype html>
<!-- Generated by shorts/build.py from shorts/divisions.json. Edit those, not this file. -->
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=1080, height=1920" />
    <title>TGM-WORLDWIDE CORPORATION — {esc(div["name"])} (20s short)</title>
    <script src="https://cdn.jsdelivr.net/npm/gsap@3.14.2/dist/gsap.min.js"></script>
    <link rel="stylesheet" href="../assets/brand.css" />
    <link rel="stylesheet" href="shorts.css" />
  </head>
  <body>
    <div id="root" data-composition-id="main" data-start="0" data-duration="{TOTAL:g}" data-width="1080" data-height="1920">
      {audio_html}

      <!-- A: logo + division ({0}–{b}s) -->
      <section id="a" class="clip lockup" data-start="0" data-duration="{b:g}" data-track-index="1">
        <img class="badge" src="../assets/logo-mark.png" alt="TGM-WORLDWIDE CORPORATION logo" />
        {name}
        {corp}
        <div class="rule"></div>
        {division}
      </section>

      <!-- Pinned logo + division during B and C -->
      <div id="chip" class="clip" data-start="{b:g}" data-duration="{round(dd - b, 2):g}" data-track-index="2">
        <img src="../assets/logo-mark.png" alt="" />
        <div class="t"><b>TGM<span>-</span>WORLDWIDE</b><small>CORPORATION</small><i>{esc(div["name"])}</i></div>
      </div>

      <!-- B: hook + services ({b}–{c}s) -->
      <section id="b" class="clip" data-start="{b:g}" data-duration="{round(c - b, 2):g}" data-track-index="1">
        <div class="hook-icon">{div["icon"]}</div>
        <h2 class="hook">{esc(div["hook"])}</h2>
        <div class="items">{items}</div>
      </section>

      <!-- C: benefits ({c}–{dd}s) -->
      <section id="c" class="clip" data-start="{c:g}" data-duration="{round(dd - c, 2):g}" data-track-index="1">
        <p class="label">WHY CHOOSE US</p>
        <div class="benefits">{cards}</div>
      </section>

      <!-- D: call to action ({dd}–{TOTAL:g}s) -->
      <section id="d" class="clip lockup cta" data-start="{dd:g}" data-duration="{round(TOTAL - dd, 2):g}" data-track-index="1">
        <img class="badge" src="../assets/logo-mark.png" alt="TGM-WORLDWIDE CORPORATION logo" />
        {name}
        {corp}
        <div class="rule"></div>
        {division}
        <p class="call">CALL TODAY</p>
        {rows}
      </section>
    </div>

    <script src="shorts.js"></script>
    <script>
      window.__timelines = window.__timelines || {{}};
      window.__timelines.main = buildShort({json.dumps(T)});
    </script>
  </body>
</html>
"""


def main() -> None:
    divisions = json.loads((ROOT / "shorts/divisions.json").read_text())
    for div in divisions:
        out = ROOT / "shorts" / f"{div['slug']}.html"
        out.write_text(build(div))
        print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
